name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Move build to docs
        run: |
          rm -rf docs
          mv dist docs

      - name: Commit docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git commit -m "Update docs from build" || echo "No changes"
          git push
